### ISSUE TITLE
@newswire/doc-to-archieml is installed, but not used

### ISSUE THREAD

**Issue by rdmurphy** [The-Politico/gootenberg#12]
While I would love if it could help here 🙃 — I noticed `gootenberg` showed up in the "things that use `@newswire/doc-to-archieml`" list on GitHub but when I came to see where, it seems to have only sneaked into the `dependencies`.

https://github.com/The-Politico/gootenberg/blob/e753bd820a985c0215b0aa4e7060264a92cd66e4/package.json#L39

**Comment by brizandrew** [comment]
Super late to this, but thanks for the heads up!
